version: '3'
services:
  db:
    container_name: db
    image: mongo
    env_file: .env
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: